---
title: ""
author: ""
date: ""
output: html_document
---

## Aula Spatial Econometrics

**Leitura prévia**
---
DRUCK, S; CARVALHO, M.S; CAMARA, G.; MONTEIRO, A.V.M (eds). Análise Espacial de Dados Geográficos - EMBRAPA 2004

- 1- Análise Espacial Geoprocessamento
- 5- Análise Espacial de Áreas

Bivand, Roger. S., Pebesma, E. J, Gomez-Rubio, V. & Pebesma, E. J (2013). Applied spatial data analysis with R

- Dados vetoriais e raster (formato sp)
- Interpolacao e Geoestatistica
- Autocorrelacao espacial

Brudson, C. and Comber, L., 2015. An introduction to R for spatial analysis and mapping

- Análise de pontos
- Autocorrelacao espacial
- Regressao ponderada geográfica

Arbia, Guiuseppe. A Primer for spatial econometrics With applications in R

- Matrizes de vizinhanca 
- Modelos espaciais regressivos

**Econometria espacial**
---
- Dados socioeconomicos agrupados em região administrativa, analisar se o setor vizinho afetava de alguma maneira em relacao as variaveis
- Incorporacao para análise epidemologica (Saude Publica), occorencia de doenca agrupada por municipio, estado. O ponto seria o espalhar da doenca, fluxo de viajens etc.

**Pacotes**
---
Luc Anselin

- Geoda
- Pysal (Pacotes para análise)

Roger Bivand

- spdep (R)
- Supervisionado pelo Luc Anselin


**Problema da Unidade de Area Modificavel**
---
Conforme voce agrega seus dados o comportamento muda, os dados podem ficar diferente


